table stock_prices

	column ticker
		dataType: string
		summarizeBy: none
		sourceColumn: ticker

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column open
		dataType: decimal
		summarizeBy: sum
		sourceColumn: open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column high
		dataType: decimal
		summarizeBy: sum
		sourceColumn: high

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column low
		dataType: decimal
		summarizeBy: sum
		sourceColumn: low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column close
		dataType: decimal
		summarizeBy: sum
		sourceColumn: close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column volume
		dataType: int64
		summarizeBy: sum
		sourceColumn: volume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition stock_prices = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "stocks_db"),
				    public_stock_prices = Source{[Schema="public",Item="stock_prices"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(public_stock_prices,{{"date", type date}, {"open", Currency.Type}, {"high", Currency.Type}, {"low", Currency.Type}, {"close", Currency.Type}, {"volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

